### ISSUE TITLE
Step to step  setup tutorial

### ISSUE THREAD

**Issue by xDoge26** [Pipetto-crypto/Chroot-Docs#5]
i want to manually setup chroot debian 10 from linux deploy not from this git . i installed box86 + wine + . how do i setup vnc server or  x11 server , run game in llvm / virgl mode , install gl4es

**Comment by Pipetto-crypto** [comment]
For termux-x11 you can just follow the guide I have in this repo under the termux-x11 folder. 

For vnc, just install tigervnc server(sudo apt install tigervnc-standalone-server tigervnc-common tigervnc-xorg-extension) then you are going to have to create an xstartup file in .vnc folder based on your Desktop Environment

**Comment by xDoge26** [comment]
> For termux-x11 you can just follow the guide I have in this repo under the termux-x11 folder.
> 
> For vnc, just install tigervnc server(sudo apt install tigervnc-standalone-server tigervnc-common tigervnc-xorg-extension) then you are going to have to create an xstartup file in .vnc folder based on your Desktop Environment

![Screenshot (94)](https://user-images.githubusercontent.com/92904701/196103171-6926a1ae-0a17-4098-b3e8-a00ac84dcc0b.png)
do you know what problems is this ?

**Comment by xDoge26** [comment]
i think i need mesa llvm but i dont know how to compile it

**Comment by Pipetto-crypto** [comment]
> i think i need mesa llvm but i dont know how to compile it

LLvmpipe is in the mesa in the repo, just install it with sudo apt install mesa mesa-utls for the arm64 version and mesa:armhf mesa-utils:armhf for the armhf version.

**Comment by xDoge26** [comment]
> 

thanks i will try it later
but i still want to learn it to compile mesa for exagear

**Comment by xDoge26** [comment]
> LLvmpipe is in the mesa in the repo, just install it with sudo apt install mesa mesa-utls for the arm64 version and mesa:armhf mesa-utils:armhf for the armhf version.

sorry all of that are installed when i compile box86 , maybe its not that one
