### ISSUE TITLE
Where Did you get rootfs file ?

### ISSUE THREAD

**Issue by xDoge26** [Pipetto-crypto/Chroot-Docs#6]
I want a small ,clean rootfs debian 10,11 proot , chroot

**Comment by Pipetto-crypto** [comment]
I made it myself, you can just use the one in this repo. It's pretty much super clean

**Comment by xDoge26** [comment]
> I made it myself, you can just use the one in this repo. It's pretty much super clean

does binfmt work in this distro ?

**Comment by Pipetto-crypto** [comment]
> > I made it myself, you can just use the one in this repo. It's pretty much super clean
> 
> does binfmt work in this distro ?

Yes, it does but you need to have a kernel with binfmt_misc support enabled.

**Comment by xDoge26** [comment]
> > > I made it myself, you can just use the one in this repo. It's pretty much super clean
> > 
> > 
> > does binfmt work in this distro ?
> 
> Yes, it does but you need to have a kernel with binfmt_misc support enabled.

sadly my kernel didnt have that . does your kernel support it

**Comment by Pipetto-crypto** [comment]
> > > > I made it myself, you can just use the one in this repo. It's pretty much super clean
> > > 
> > > 
> > > does binfmt work in this distro ?
> > 
> > 
> > Yes, it does but you need to have a kernel with binfmt_misc support enabled.
> 
> sadly my kernel didnt have that . does your kernel support it

It has but I had to compile a kernel with binfmt_misc support as well.
