### ISSUE TITLE
Virgl in proot distro

### ISSUE THREAD

**Issue by xDoge26** [Pipetto-crypto/Chroot-Docs#7]
do you know how to make it work ? , since chroot is slower and outdated

**Comment by Pipetto-crypto** [comment]
Chroot is way faster than proot, I don't know where you got that info but this is the accurate one:

https://wiki.termux.com/wiki/PRoot

**Comment by xDoge26** [comment]
> do you know how to make it work ? , since chroot is slower and outdated

im not sure but i got 300fps in proot glxgears and 150fps in chroot glxgear . its the same with box86 + wine performance between proot and chroot

**Comment by Pipetto-crypto** [comment]
It's fact that chroot has more perfs than proot. Regardless I will close this issue since I can't help you with this
